version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "3005:3005"
    environment:
      - MONGO_URI=mongodb://mongo:27017/task-tracker
      - JWT_SECRET=your_jwt_secret
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  migrate:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: ["node", "migrations/seedStatuses.js"]
    environment:
      - MONGO_URI=mongodb://mongo:27017/task-tracker
    depends_on:
      - mongo

volumes:
  mongo-data: